### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by esadakcam** [stevenlsw/hoi-forecast#3]
Hi,

Thanks for sharing your source code.

I am getting "EOFError: Ran out of input" error while evaluating future hand trajectory or future interaction hotspots. I have followed the steps on the README. All of the error trace is following:
```(base) C:\Users\mesad\projects\bitirme\hoi-forecast>python traineval.py --evaluate --ek_version=ek100 --resume=model.pth.tar
Using 1 GPUs !
=> loading checkpoint 'model.pth.tar'
Loaded checkpoint from epoch 35, starting from there
Loading validation samples: 100%|██████████████████████████████████████████████████████████████████████████████████| 3513/3513 [00:00<00:00, 8801.58it/s]
Loading eval samples: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 401/401 [00:00<00:00, 5768.16it/s]
C:\Users\mesad\miniconda3\lib\site-packages\torch\utils\data\dataloader.py:563: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 12 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
evaluation dataset size: 401
evaluate epoch 35
Traceback (most recent call last):
  File "C:\Users\mesad\projects\bitirme\hoi-forecast\traineval.py", line 125, in <module>
    main(args)
  File "C:\Users\mesad\projects\bitirme\hoi-forecast\traineval.py", line 76, in main
    epoch_pass(Exception ignored in: <function lmdbdict.__del__ at 0x000002084936B0D0>

  File "C:\Users\mesad\projects\bitirme\hoi-forecast\netscripts\epoch_feat.py", line 31, in epoch_pass
Traceback (most recent call last):
  File "C:\Users\mesad\miniconda3\lib\site-packages\lmdbdict\lmdbdict.py", line 184, in __del__
    for batch_idx, sample in enumerate(loader):
  File "C:\Users\mesad\miniconda3\lib\site-packages\torch\utils\data\dataloader.py", line 444, in __iter__
    if self.mode == 'w':
AttributeError    return self._get_iterator():
  File "C:\Users\mesad\miniconda3\lib\site-packages\torch\utils\data\dataloader.py", line 390, in _get_iterator
'lmdbdict' object has no attribute 'mode'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\mesad\miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
  File "C:\Users\mesad\miniconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1077, in __init__
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\mesad\miniconda3\lib\multiprocessing\spawn.py", line 126, in _main
    w.start()
  File "C:\Users\mesad\miniconda3\lib\multiprocessing\process.py", line 121, in start
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
    self._popen = self._Popen(self)
  File "C:\Users\mesad\miniconda3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\mesad\miniconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\mesad\miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\mesad\miniconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_features_loader.<locals>.<lambda>'```

**Comment by stevenlsw** [comment]
Hi esadakcam, could you please try disable multiprocess or decreasing number of workers by appending `--workers=4` in your command, see if the error still exists?

**Comment by esadakcam** [comment]
Hi,

Thanks for sparing time but it is same. I have tried with 1 and 4 workers but the  "EOFError: Ran out of input" was not fixed.  The shell command and error trace are shown belown:
 ``` (fhoi) C:\Users\mesad\projects\bitirme\hoi-forecast>python traineval.py --evaluate --ek_version=ek100 --resume=model.pth.tar --traj_only --workers=1
=> loading checkpoint 'model.pth.tar'
Loaded checkpoint from epoch 35, starting from there
Loading validation samples: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3513/3513 [00:00<00:00, 4922.06it/s]
Loading eval samples: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 401/401 [00:00<00:00, 3269.91it/s]
evaluation dataset size: 3513
evaluate epoch 35
Traceback (most recent call last):
  File "traineval.py", line 125, in <module>
    main(args)
  File "traineval.py", line 96, in main
    num_samples=args.num_samples)
  File "C:\Users\mesad\projects\bitirme\hoi-forecast\netscripts\epoch_feat.py", line 31, in epoch_pass
    for batch_idx, sample in enumerate(loader):
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_features_loader.<locals>.<lambda>'

(fhoi) C:\Users\mesad\projects\bitirme\hoi-forecast>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\mesad\miniconda3\envs\fhoi\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input ```

**Comment by stevenlsw** [comment]
could you do it with 0. Windows might have this mp problems as i know. There should be no such error on other platforms. 

Best

**Comment by esadakcam** [comment]
Hi,

I have tried to run the 'python traineval.py --evaluate --ek_version=ek100 --resume=model.pth.tar --traj_only --workers=0' command on m1 macbook air. I got KeyError due to the lmdbdict library.  I have run it with python3.9 but I assume this would not be problem. The all trace can be shown bellow:
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/55852045/193472680-7bbaff20-ab84-45fa-bb21-2487e3efaf8a.png">

**Comment by stevenlsw** [comment]
hi, please use the provided python3.6 env given the utf-8 encoding is
slightly different across versions.

**Comment by esadakcam** [comment]
Future note for new comings, I had some issues about running the model on the GPU but I removed and reinstalled torch with cuda version 11 and it is fixed.

**Comment by Lynepe** [comment]
Hi，can I ask you for your requirements?
especially the version of your modules.thx a lot.
 error trace are shown below:
 
![image](https://github.com/stevenlsw/hoi-forecast/assets/145852861/75fbb7be-8062-4246-aba4-4a8e3d2e9d0d)

**Comment by Lynepe** [comment]
Thank you all the same.
